# Generated by Django 4.2.2 on 2023-07-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='foto_perfil',
            field=models.URLField(blank=True, null=True),
        ),
    ]
