# Generated by Django 4.2.2 on 2023-07-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_vendedor_horario_abertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto_poduto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
