# Generated by Django 4.2.2 on 2023-07-02 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_produto_foto_poduto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='foto_poduto',
            new_name='foto_produto',
        ),
    ]
